### ISSUE TITLE
Feature Request: Custom Resource Hacker URL

### ISSUE THREAD

**Issue by elliott-pd** [evshiron/node-resourcehacker#1]
The latest stable version of Resource Hacker isn't properly replacing file icons. This seems to have been fixed in the latest beta version.

As the download URL is hard coded, I am suggesting allowing a custom url to be passed as part of the options this would allow for a specific version to be downloaded every time rather than always getting the latest version from 'http://www.angusj.com/resourcehacker/resource_hacker.zip'.

Changes required are minimal, however an update for nwjs-builder would also need to be made to support those parameters being passed through as well.

Edit: Added a pull request.

**Comment by evshiron** [comment]
`node-resourcehacker` 1.2.1 has been released and should now have the changes on.
I have tested against and confirm that it is the current stable release of Resource Hacker that causes the problem, while previous stable release and current beta release works well.
